#!/bin/bash
# Build script for generating the static GitHub Pages site.
# This replaces the inline heredoc in the GitHub Action workflow.
#
# The dashboard source now lives in src/dashboard, but we continue to emit the
# built static site to the repository root _site/ directory so that GitHub
# Pages, Playwright tests, and CLI tooling can keep their existing assumptions.

set -e

# Resolve important paths relative to this script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
SCRIPTS_DIR="${PROJECT_ROOT}/scripts/ops"
SITE_DIR="${PROJECT_ROOT}/_site"
DASHBOARD_DIR="${SCRIPT_DIR}"

echo "Building static site..."
echo "Project root: ${PROJECT_ROOT}"
echo "Dashboard dir: ${DASHBOARD_DIR}"
echo "Output dir: ${SITE_DIR}"

# Create _site directory at project root
mkdir -p "${SITE_DIR}"

# Copy the enhanced template
cp "${DASHBOARD_DIR}/templates/index.html" "${SITE_DIR}/index.html"

# Copy modular CSS and JavaScript structure
echo "Copying modular CSS and JavaScript files..."
# Clean old files first to prevent nested directories and stale code
rm -rf "${SITE_DIR}/css" "${SITE_DIR}/js"
cp -r "${DASHBOARD_DIR}/css" "${SITE_DIR}/css"
cp -r "${DASHBOARD_DIR}/js" "${SITE_DIR}/js"
echo "✓ Copied modular CSS and JavaScript files (cleaned old files first)"

# Copy advanced features CSS (if exists for backwards compatibility)
if [ -f "${DASHBOARD_DIR}/advanced-features.css" ]; then
    cp "${DASHBOARD_DIR}/advanced-features.css" "${SITE_DIR}/advanced-features.css"
    echo "✓ Copied advanced-features.css"
fi

# Copy data files
mkdir -p "${SITE_DIR}/data"

# Note: all_metrics.json is generated by the Python script in the GitHub Actions workflow
# This fallback logic is only for local builds outside the CI/CD pipeline
if [ -f "${SITE_DIR}/data/all_metrics.json" ]; then
    # Data already exists in _site, keep it
    echo "✓ Found existing all_metrics.json"
elif [ -f "${PROJECT_ROOT}/data/all_metrics.json" ]; then
    cp "${PROJECT_ROOT}/data/all_metrics.json" "${SITE_DIR}/data/"
    echo "✓ Copied all_metrics.json from data/"
else
    echo "⚠ Warning: all_metrics.json not found (will be generated by Python script in workflow)"
fi

# Helper to copy a dashboard data file if it exists
copy_dashboard_data_file() {
    local filename="$1"
    if [ -f "${DASHBOARD_DIR}/data/${filename}" ]; then
        cp "${DASHBOARD_DIR}/data/${filename}" "${SITE_DIR}/data/"
        echo "✓ Copied ${filename}"
    else
        echo "⚠ Warning: ${filename} not found"
    fi
}

copy_dashboard_data_file "source_mix_targets.json"
copy_dashboard_data_file "source_catalog.json"
copy_dashboard_data_file "source_pipeline_status.json"

if [ -f "${DASHBOARD_DIR}/data/quality_alerts.json" ]; then
    cp "${DASHBOARD_DIR}/data/quality_alerts.json" "${SITE_DIR}/data/"
    echo "✓ Copied quality_alerts.json"
fi

if [ -f "${DASHBOARD_DIR}/data/quality_waivers.json" ]; then
    cp "${DASHBOARD_DIR}/data/quality_waivers.json" "${SITE_DIR}/data/"
    echo "✓ Copied quality_waivers.json"
fi

if [ -f "${DASHBOARD_DIR}/data/pipeline_alerts.json" ]; then
    cp "${DASHBOARD_DIR}/data/pipeline_alerts.json" "${SITE_DIR}/data/"
    echo "✓ Copied pipeline_alerts.json"
fi

if [ -f "${DASHBOARD_DIR}/data/pipeline_observations.json" ]; then
    cp "${DASHBOARD_DIR}/data/pipeline_observations.json" "${SITE_DIR}/data/"
    echo "✓ Copied pipeline_observations.json"
fi

if [ -f "${DASHBOARD_DIR}/data/pipeline_run_history.json" ]; then
    cp "${DASHBOARD_DIR}/data/pipeline_run_history.json" "${SITE_DIR}/data/"
    echo "✓ Copied pipeline_run_history.json"
fi

if [ -f "${DASHBOARD_DIR}/data/sla_targets.json" ]; then
    cp "${DASHBOARD_DIR}/data/sla_targets.json" "${SITE_DIR}/data/"
    echo "✓ Copied sla_targets.json"
fi

# Copy favicon
if [ -f "${DASHBOARD_DIR}/favicon.svg" ]; then
    cp "${DASHBOARD_DIR}/favicon.svg" "${SITE_DIR}/favicon.svg"
    echo "✓ Copied favicon"
elif [ -f "${PROJECT_ROOT}/data/favicon.svg" ]; then
    cp "${PROJECT_ROOT}/data/favicon.svg" "${SITE_DIR}/favicon.svg"
    echo "✓ Copied favicon from data/"
fi

# Copy any metric files
if [ -d "${PROJECT_ROOT}/data/metrics" ]; then
    cp -r "${PROJECT_ROOT}/data/metrics" "${SITE_DIR}/data/" 2>/dev/null || true
fi

if [ -d "${PROJECT_ROOT}/data/reports" ]; then
    cp -r "${PROJECT_ROOT}/data/reports" "${SITE_DIR}/data/" 2>/dev/null || true
fi

# Export quota and manifest data for dashboard
if [ -f "${SCRIPTS_DIR}/export_quota_dashboard_data.py" ]; then
    echo "Exporting quota and manifest data..."
    python3 "${SCRIPTS_DIR}/export_quota_dashboard_data.py" \
        --ledger "${PROJECT_ROOT}/data/ledger/crawl_ledger.db" \
        --manifests "${PROJECT_ROOT}/data/manifests" \
        --output-dir "${DASHBOARD_DIR}/data" \
        --quota-days 30

    if [ $? -eq 0 ]; then
        echo "✓ Dashboard data exported successfully"
        # Copy exported files to _site/data
        if [ -f "${DASHBOARD_DIR}/data/quota_status.json" ]; then
            cp "${DASHBOARD_DIR}/data/quota_status.json" "${SITE_DIR}/data/"
            echo "✓ Copied quota_status.json"
        fi
        if [ -f "${DASHBOARD_DIR}/data/manifest_analytics.json" ]; then
            cp "${DASHBOARD_DIR}/data/manifest_analytics.json" "${SITE_DIR}/data/"
            echo "✓ Copied manifest_analytics.json"
        fi
    else
        echo "⚠ Warning: Failed to export dashboard data"
    fi
else
    echo "⚠ Warning: export_quota_dashboard_data.py not found in ${SCRIPTS_DIR}"
fi

# Generate advanced visualization data (Sankey flow, text distributions)
# Note: This script expects _site/data to exist and will create the files there
if [ -f "${SCRIPTS_DIR}/generate_advanced_viz_data.py" ]; then
    echo "Generating advanced visualization data..."
    (cd "${PROJECT_ROOT}" && python "scripts/ops/generate_advanced_viz_data.py") || echo "⚠ Warning: Advanced viz data generation failed"
else
    echo "⚠ Warning: generate_advanced_viz_data.py not found in ${SCRIPTS_DIR}"
fi

echo "✓ Site built successfully in ${SITE_DIR}/"
ls -lh "${SITE_DIR}/"
