# Prometheus Configuration for Somali NLP Data Pipelines
# This configuration sets up metrics collection for monitoring pipeline health

global:
  scrape_interval: 15s        # Scrape targets every 15 seconds
  evaluation_interval: 15s    # Evaluate rules every 15 seconds
  external_labels:
    cluster: 'somali-nlp'
    environment: 'production'

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Rule files for alerting
rule_files:
  - 'alerts.yml'

# Scrape configurations
scrape_configs:
  # Prometheus exporter service
  - job_name: 'somali-nlp-pipelines'

    # File-based service discovery for dynamic target management
    file_sd_configs:
      - files:
        - 'targets.json'
        refresh_interval: 30s

    # Metric relabeling for consistent naming
    metric_relabel_configs:
      # Extract metric type from metric name
      - source_labels: [__name__]
        regex: 'pipeline_(.*)'
        target_label: 'metric_type'
        replacement: '$1'

      # Normalize source labels
      - source_labels: [source]
        regex: '(.+)'
        target_label: 'data_source'
        replacement: '$1'

  # Node exporter for system metrics (optional)
  - job_name: 'node'
    static_configs:
      - targets: []
        # - 'localhost:9100'
