#!/bin/bash
# Build script for generating the static GitHub Pages site
# This replaces the inline heredoc in the GitHub Action workflow

set -e

echo "Building static site..."

# Create _site directory
mkdir -p _site

# Copy the enhanced template
cp dashboard/templates/index.html _site/index.html

# Copy modular CSS and JavaScript structure
echo "Copying modular CSS and JavaScript files..."
# Clean old files first to prevent nested directories and stale code
rm -rf _site/css _site/js
cp -r dashboard/css _site/css
cp -r dashboard/js _site/js
echo "✓ Copied modular CSS and JavaScript files (cleaned old files first)"

# Copy advanced features CSS (if exists for backwards compatibility)
if [ -f "dashboard/advanced-features.css" ]; then
    cp dashboard/advanced-features.css _site/advanced-features.css
    echo "✓ Copied advanced-features.css"
fi

# Copy data files
mkdir -p _site/data

# Note: all_metrics.json is generated by the Python script in the GitHub Actions workflow
# This fallback logic is only for local builds outside the CI/CD pipeline
if [ -f "_site/data/all_metrics.json" ]; then
    # Data already exists in _site, keep it
    echo "✓ Found existing all_metrics.json"
elif [ -f "data/all_metrics.json" ]; then
    cp data/all_metrics.json _site/data/
    echo "✓ Copied all_metrics.json from data/"
else
    echo "⚠ Warning: all_metrics.json not found (will be generated by Python script in workflow)"
fi

# Copy source mix targets configuration
if [ -f "dashboard/data/source_mix_targets.json" ]; then
    cp dashboard/data/source_mix_targets.json _site/data/
    echo "✓ Copied source_mix_targets.json"
else
    echo "⚠ Warning: source_mix_targets.json not found"
fi

if [ -f "dashboard/data/source_catalog.json" ]; then
    cp dashboard/data/source_catalog.json _site/data/
    echo "✓ Copied source_catalog.json"
else
    echo "⚠ Warning: source_catalog.json not found"
fi

if [ -f "dashboard/data/source_pipeline_status.json" ]; then
    cp dashboard/data/source_pipeline_status.json _site/data/
    echo "✓ Copied source_pipeline_status.json"
else
    echo "⚠ Warning: source_pipeline_status.json not found"
fi

if [ -f "dashboard/data/quality_alerts.json" ]; then
    cp dashboard/data/quality_alerts.json _site/data/
    echo "✓ Copied quality_alerts.json"
fi

if [ -f "dashboard/data/quality_waivers.json" ]; then
    cp dashboard/data/quality_waivers.json _site/data/
    echo "✓ Copied quality_waivers.json"
fi

# Copy favicon
if [ -f "dashboard/favicon.svg" ]; then
    cp dashboard/favicon.svg _site/favicon.svg
    echo "✓ Copied favicon"
elif [ -f "data/favicon.svg" ]; then
    cp data/favicon.svg _site/favicon.svg
    echo "✓ Copied favicon from data/"
fi

# Copy any metric files
if [ -d "data/metrics" ]; then
    cp -r data/metrics _site/data/ 2>/dev/null || true
fi

if [ -d "data/reports" ]; then
    cp -r data/reports _site/data/ 2>/dev/null || true
fi

# Generate advanced visualization data (Sankey flow, text distributions)
# Note: This script expects _site/data to exist and will create the files there
if [ -f "scripts/generate_advanced_viz_data.py" ]; then
    echo "Generating advanced visualization data..."
    python scripts/generate_advanced_viz_data.py || echo "⚠ Warning: Advanced viz data generation failed"
else
    echo "⚠ Warning: scripts/generate_advanced_viz_data.py not found"
fi

echo "✓ Site built successfully in _site/"
ls -lh _site/
