#!/bin/bash
# Build script for generating the static GitHub Pages site
# This replaces the inline heredoc in the GitHub Action workflow

set -e

echo "Building static site..."

# Create _site directory
mkdir -p _site

# Copy the enhanced template
cp dashboard/templates/index.html _site/index.html

# Copy advanced features JavaScript and CSS files
echo "Copying advanced features files..."
cp dashboard/theme-manager.js _site/theme-manager.js
cp dashboard/filter-manager.js _site/filter-manager.js
cp dashboard/export-manager.js _site/export-manager.js
cp dashboard/advanced-charts.js _site/advanced-charts.js
cp dashboard/comparison-mode.js _site/comparison-mode.js
cp dashboard/advanced-features.css _site/advanced-features.css
echo "✓ Copied advanced features files"

# Copy data files
mkdir -p _site/data

# Note: all_metrics.json is generated by the Python script in the GitHub Actions workflow
# This fallback logic is only for local builds outside the CI/CD pipeline
if [ -f "_site/data/all_metrics.json" ]; then
    # Data already exists in _site, keep it
    echo "✓ Found existing all_metrics.json"
elif [ -f "data/all_metrics.json" ]; then
    cp data/all_metrics.json _site/data/
    echo "✓ Copied all_metrics.json from data/"
else
    echo "⚠ Warning: all_metrics.json not found (will be generated by Python script in workflow)"
fi

# Copy favicon
if [ -f "dashboard/favicon.svg" ]; then
    cp dashboard/favicon.svg _site/favicon.svg
    echo "✓ Copied favicon"
elif [ -f "data/favicon.svg" ]; then
    cp data/favicon.svg _site/favicon.svg
    echo "✓ Copied favicon from data/"
fi

# Copy any metric files
if [ -d "data/metrics" ]; then
    cp -r data/metrics _site/data/ 2>/dev/null || true
fi

if [ -d "data/reports" ]; then
    cp -r data/reports _site/data/ 2>/dev/null || true
fi

# Generate advanced visualization data (Sankey flow, text distributions)
# Note: This script expects _site/data to exist and will create the files there
if [ -f "scripts/generate_advanced_viz_data.py" ]; then
    echo "Generating advanced visualization data..."
    python scripts/generate_advanced_viz_data.py || echo "⚠ Warning: Advanced viz data generation failed"
else
    echo "⚠ Warning: scripts/generate_advanced_viz_data.py not found"
fi

echo "✓ Site built successfully in _site/"
ls -lh _site/
