#!/usr/bin/env bash
# Setup Gitleaks Pre-Commit Hook
# Automatically scans staged files for secrets before each commit
# Part of Somali NLP Dialect Classifier security measures

set -e

HOOK_DIR=".git/hooks"
HOOK_FILE="$HOOK_DIR/pre-commit"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "=================================="
echo "Gitleaks Pre-Commit Hook Setup"
echo "=================================="
echo ""

# Check if gitleaks is installed
if ! command -v gitleaks &> /dev/null; then
    echo "❌ ERROR: gitleaks is not installed!"
    echo ""
    echo "Install gitleaks:"
    echo "  macOS:   brew install gitleaks"
    echo "  Linux:   https://github.com/gitleaks/gitleaks#installation"
    echo ""
    exit 1
fi

echo "✓ Gitleaks found: $(gitleaks version)"
echo ""

# Check if .gitleaks.toml exists
if [ ! -f "$PROJECT_ROOT/.gitleaks.toml" ]; then
    echo "❌ ERROR: .gitleaks.toml not found in project root!"
    exit 1
fi

echo "✓ Configuration file found: .gitleaks.toml"
echo ""

# Create hooks directory if it doesn't exist
mkdir -p "$HOOK_DIR"

# Backup existing pre-commit hook if it exists
if [ -f "$HOOK_FILE" ] && [ ! -L "$HOOK_FILE" ]; then
    BACKUP_FILE="${HOOK_FILE}.backup.$(date +%Y%m%d_%H%M%S)"
    echo "⚠️  Existing pre-commit hook found. Backing up to:"
    echo "   $BACKUP_FILE"
    mv "$HOOK_FILE" "$BACKUP_FILE"
    echo ""
fi

# Create the pre-commit hook
cat > "$HOOK_FILE" << 'EOF'
#!/usr/bin/env bash
# Gitleaks Pre-Commit Hook
# Automatically scans staged files for secrets before commit
# Generated by scripts/setup-gitleaks-hook.sh

set -e

echo "🔍 Scanning staged files for secrets..."

# Run gitleaks on staged changes only (fast!)
if ! gitleaks protect --config .gitleaks.toml --staged --verbose; then
    echo ""
    echo "❌ COMMIT REJECTED: Secrets detected in staged files!"
    echo ""
    echo "What to do:"
    echo "  1. Remove the detected secrets from your files"
    echo "  2. Use environment variables or .env files (not committed)"
    echo "  3. Re-stage your files: git add <file>"
    echo "  4. Try committing again"
    echo ""
    echo "To bypass this check (NOT RECOMMENDED):"
    echo "  git commit --no-verify"
    echo ""
    exit 1
fi

echo "✓ No secrets detected. Proceeding with commit..."
EOF

# Make the hook executable
chmod +x "$HOOK_FILE"

echo "✅ Pre-commit hook installed successfully!"
echo ""
echo "Location: $HOOK_FILE"
echo ""
echo "────────────────────────────────────────────────"
echo "How it works:"
echo "────────────────────────────────────────────────"
echo "• Runs automatically before every git commit"
echo "• Scans ONLY staged files (super fast!)"
echo "• Blocks commit if secrets are detected"
echo "• Uses configuration from .gitleaks.toml"
echo ""
echo "────────────────────────────────────────────────"
echo "Manual usage:"
echo "────────────────────────────────────────────────"
echo "  make secrets-check    # Check staged files"
echo "  make secrets-scan     # Full repo scan"
echo ""
echo "────────────────────────────────────────────────"
echo "To bypass (emergency only):"
echo "────────────────────────────────────────────────"
echo "  git commit --no-verify"
echo ""
echo "✅ Setup complete! Your commits are now protected."
echo ""
